gdomingu/honma-api

app/assets/stylesheets/dialects.scss
app/assets/stylesheets/scaffolds.scss
app/controllers/dialects_controller.rb
app/helpers/dialects_helper.rb
app/models/dialect.rb
app/views/dialects/_dialect.json.jbuilder
app/views/dialects/_form.html.erb
app/views/dialects/edit.html.erb
app/views/dialects/index.html.erb
app/views/dialects/index.json.jbuilder
app/views/dialects/new.html.erb
app/views/dialects/show.html.erb
app/views/dialects/show.json.jbuilder
config/routes.rb
db/migrate/20201229063625_create_dialects.rb
db/schema.rb

scaffold for dialects

---

app/controllers/grammars_controller.rb
app/models/grammar.rb
app/views/grammars/_form.html.erb
app/views/grammars/edit.html.erb
app/views/grammars/index.html.erb
app/views/grammars/new.html.erb
app/views/grammars/show.html.erb
config/routes.rb
db/migrate/20201230043444_create_grammars.rb
db/schema.rb

Added Grammars table, controller and views.

Add tables

---

app/views/examples/_form.html.erb
app/views/grammars/_form.html.erb

add select box when creating a new grammar.

add form.select for grammaars

---

app/controllers/examples_controller.rb
app/controllers/grammars_controller.rb
app/views/examples/index.html.erb
app/views/grammars/index.html.erb

display names instead of ids and prevent n+1.

display names instead of ids and prevent n+1

---

app/controllers/api/dialects_controller.rb
app/models/dialect.rb
app/models/grammar.rb
config/routes.rb

Created API endpoints for language data.

Api endpoints

---

db/migrate/20210103004711_add_name_column_grammars.rb
db/schema.rb
db/seeds.rb

Adds label column to grammars and seed file
you can run the seed file with `bundle exec rake db:seed` or `rake db:seed`

Adds label column to grammars and seed file

---

app/views/home/index.html.erb

add links to grammar/ example pages, changed homepage title

add links to grammar/ example pages, changed homepage title

---

app/views/examples/_form.html.erb
app/views/grammars/_form.html.erb

Fixes select for example form and added label to grammar form

---

app/views/examples/_form.html.erb

Adds clip_name to edit form for examples

---

app/controllers/dialects_controller.rb
app/views/dialects/_form.html.erb
app/views/dialects/show.html.erb
app/views/examples/show.html.erb
db/migrate/20210106035306_add_column_to_dialects.rb
db/schema.rb

Added start_btn_text and next_btn_text columns. Added those in forms and shows in view.

Add colums to dialects

---

app/controllers/api/dialects_controller.rb

add btn texts in api controller

add btn texts in api controller

---

app/views/grammars/index.html.erb
app/views/grammars/show.html.erb

add label to grammar show page and grammar index page

add label to grammar show page and grammar index page

---

app/controllers/api/dialects_controller.rb
app/controllers/grammars_controller.rb

grammars are sorted by position in api controller

grammars are sorted by position and dialects are sorted by alphabetically in api controller

---

app/controllers/grammars_controller.rb

I forgot to add label to the strong params in the controller. This PR fixes it!

Adds label to strong params in grammars controller so can update

---

app/controllers/grammars_controller.rb
app/views/grammars/index.html.erb

It passes dialect_id from index page to new page

pass dialect_id from index page to new page

---

app/controllers/examples_controller.rb
app/views/examples/_form.html.erb
app/views/examples/index.html.erb
app/views/examples/show.html.erb
db/migrate/20210111185447_remove_clip_name_from_examples.rb
db/schema.rb

Removed clip_name column and the references to it in any .html.erb file.

Delete clip name

---

app/controllers/examples_controller.rb
app/views/examples/index.html.erb
app/views/examples/show.html.erb

Display dialect name in example index and show

Display dialect name in example index and show

---

app/views/examples/_form.html.erb

Displays dialect name in example create and edit page

display dialect name in example create and edit page

---

app/controllers/grammars_controller.rb
app/views/examples/_form.html.erb
app/views/grammars/show.html.erb

add new example page to grammar show page.

add new example page to grammar show page.

---

app/controllers/api/dialects_controller.rb
app/controllers/grammars_controller.rb
app/views/grammars/_form.html.erb
app/views/grammars/index.html.erb
app/views/grammars/show.html.erb
db/migrate/20210124014415_add_commonness_to_grammar.rb
db/schema.rb

Added commonness column to grammar. Fixed controller and form.

Added commonness column to grammar. Fixed controller and form.

---

app/assets/stylesheets/quizzes.scss
app/controllers/grammars_controller.rb
app/controllers/quizes_controller.rb
app/controllers/quizzes_controller.rb
app/helpers/quizzes_helper.rb
app/models/grammar.rb
app/models/quiz.rb
app/views/grammars/index.html.erb
app/views/grammars/show.html.erb
app/views/quizzes/_form.html.erb
app/views/quizzes/edit.html.erb
app/views/quizzes/index.html.erb
app/views/quizzes/new.html.erb
app/views/quizzes/show.html.erb
config/routes.rb
db/migrate/20210127001712_create_quizzes.rb
db/schema.rb

Added Quiz table and CRUD functionality.
Quiz is displayed in grammar show page.

Quiz table

---

app/controllers/api/dialects_controller.rb

Added quizzes in api controller.

add quizzes in api controller

---

app/controllers/home_controller.rb
app/views/home/index.html.erb

Added links to sign in and to log out in homepage.

Added user table and links to sign in and to log out in homepage.

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/users/sessions_controller.rb
app/models/user.rb
config/routes.rb
db/migrate/20210308202700_add_authentication_token_to_users.rb
db/schema.rb

Added simple token authentication gem and user controller for generating token.

Devise token auth

---

app/controllers/application_controller.rb

Added code to to prevent CSRF token. API signup call works.

Added code to to prevent CSRF token.

---

Gemfile
Gemfile.lock
app/controllers/place_infos_controller.rb
app/views/place_infos/_form.html.erb
app/views/place_infos/edit.html.erb
app/views/place_infos/index.html.erb
app/views/place_infos/new.html.erb
app/views/place_infos/show.html.erb
config/routes.rb

Go to `http://localhost:3000/place_infos`
Show page:
Create page:
Edit page:

Create route, index and show controller for PlaceInfo

---

app/controllers/place_infos_controller.rb
app/views/dialects/index.html.erb
app/views/place_infos/index.html.erb

User can go to selected dialect's place info page 😸 
https://user-images.githubusercontent.com/60206746/141663538-24a6893f-3fa0-43ac-b630-4f5e89565c63.mov

Navigate place info page from dialect page

---

app/views/dialects/show.html.erb

Display place infos name in each dialect page. This navigates to go to place info page for detail. Also add create path for place info.
https://user-images.githubusercontent.com/60206746/143650298-afb53369-ba25-44ab-a189-e8e786189946.mov

shows place infos and links in each dialect page

---

Gemfile
Gemfile.lock
app/controllers/place_infos_controller.rb
app/models/place_info.rb
app/views/place_infos/_form.html.erb
app/views/place_infos/show.html.erb
config/environments/development.rb
config/webpacker.yml

It shows and resizes the pictures in place info page.

Upload pictures place info

---

app/controllers/dialects_controller.rb
app/models/dialect.rb
app/views/dialects/_form.html.erb
app/views/dialects/show.html.erb

User can upload default picture in dialect page.
https://user-images.githubusercontent.com/60206746/145683679-5652ec08-70e0-4a3c-8c73-734614c7bcc5.mov

upload/ show default picture on dialect page

---

app/controllers/place_infos_controller.rb
app/views/place_infos/_form.html.erb
app/views/place_infos/index.html.erb
app/views/place_infos/show.html.erb
db/migrate/20211212174544_add_category_to_place_info.rb
db/migrate/20211212181035_remove_categories_from_dialect.rb
db/schema.rb

User can select category when creating place info.
https://user-images.githubusercontent.com/60206746/145726709-57b8000e-694c-4873-a57d-99d948648c62.mov

Add category column to place info table

---

app/controllers/dialects_controller.rb
app/controllers/place_infos_controller.rb
app/views/dialects/_form.html.erb
app/views/dialects/show.html.erb
app/views/place_infos/_form.html.erb
app/views/place_infos/show.html.erb
db/migrate/20211212204240_add_description_to_dialect.rb
db/migrate/20211212204253_add_description_to_place_info.rb
db/schema.rb

Added description column to dialect and place info table. User can user CRUD on both tables.

Add description column to dialect and place info table

---

app/controllers/dialects_controller.rb
app/views/dialects/index.html.erb

User can sort by area in dialects page.
https://user-images.githubusercontent.com/60206746/147424085-6552f133-1299-43a0-a1eb-c7bfaac7b1da.mov

sort by area

---

app/views/dialects/_form.html.erb

Displays default image when it exists in edit page.
https://user-images.githubusercontent.com/60206746/147510991-0651c81b-86e8-4591-ba07-f43516429748.mov

displays image when editing

---

app/controllers/api/dialects_controller.rb

Added description and area attributes to api controller.

add attributes

---

app/controllers/api/dialects_controller.rb

Add place_info data in api/dialects

---

app/models/place_info.rb
app/views/place_infos/_form.html.erb

This PR limits the length of description for place info.
https://user-images.githubusercontent.com/60206746/148706998-88f54e2b-591d-4cf7-9d1c-a4ceab8bca05.mov

Add validation for place info description

---

app/controllers/api/dialects_controller.rb
app/controllers/place_infos_controller.rb
app/views/place_infos/_form.html.erb
app/views/place_infos/show.html.erb
db/migrate/20220118051735_add_url_to_place_info.rb
db/migrate/20220118055318_remove_url_from_place_info.rb
db/schema.rb

Added website column to place info.
Edited CRUD for admin side and api controller.

Add website column to place info

---

Gemfile
Gemfile.lock
app/controllers/graphql_controller.rb
app/graphql/honma_api_schema.rb
app/graphql/mutations/base_mutation.rb
app/graphql/types/base_argument.rb
app/graphql/types/base_connection.rb
app/graphql/types/base_edge.rb
app/graphql/types/base_enum.rb
app/graphql/types/base_field.rb
app/graphql/types/base_input_object.rb
app/graphql/types/base_interface.rb
app/graphql/types/base_object.rb
app/graphql/types/base_scalar.rb
app/graphql/types/base_union.rb
app/graphql/types/dialect_type.rb
app/graphql/types/mutation_type.rb
app/graphql/types/node_type.rb
app/graphql/types/place_info_type.rb
app/graphql/types/query_type.rb
config/routes.rb

Add GraphQL and query for PlaceInfo

Add graphql for PlaceInfo

---

app/controllers/api/dialects_controller.rb
app/graphql/types/query_type.rb

Remove place infos from dialects controller

---

Gemfile
Gemfile.lock
Rakefile
app/graphql/specs/queries/place_info_type_spec.rb
schema.graphql
schema.json
spec/factories/dialects.rb
spec/factories/users.rb
spec/rails_helper.rb

Need to add specs for place_infos graphql query.
Added 2 gems, please run `bundle install`
[Card #37](https://trello.com/c/Bqn2HguB)

[Card #37] Use factory bot to add Graphql specs

---

app/models/example.rb
spec/models/example_spec.rb

Example should be added with language and sentences.
Go to grammars page
http://localhost:3000/grammars/8
Added validations so it won't create example without language and sentences.
https://github.com/gdomingu/honma-api/assets/60206746/c7fdb01e-0b4a-4052-8473-581643d4de68
[Card #38](https://trello.com/c/xAEMGWP4/123-card-38-example-shouldnt-be-added-when-the-language-isnt-selected)

[Card #38] Add validation when creating example

---

app/models/quiz.rb
spec/models/quiz_spec.rb

Quiz should be added with a question and an answer.
Go to quiz page
ex: http://localhost:3000/quizzes/1
Added validations so it won't create quiz without a question and an answer.
https://github.com/gdomingu/honma-api/assets/60206746/8768cfb3-c6b4-40ac-96eb-7dd238eb869f
[Card #39](https://trello.com/c/mr7eiifg)

[Card #39] Add validation for quiz

---

spec/controllers/dialects_controller_spec.rb
spec/controllers/quiz_controller_spec.rb
spec/factories/dialects.rb
spec/factories/grammars.rb
spec/factories/quizzes.rb

Add factory for grammar and quiz
Add factories and apply them in tests.

[Card #41] Add factory

---

Gemfile
Gemfile.lock
app/controllers/api/dialects_controller.rb
app/controllers/api/grammars_controller.rb
config/environments/development.rb
config/routes.rb
spec/controllers/api/dialects_controller_spec.rb
spec/controllers/api/grammars_controller_spec.rb

It was all loading dialects, grammars, quizzes data at once when loading the page. Need to refactor to load only necessary data per page.
- Added bullet gem
- Separated and created a new api grammar controller
Before:
dialects_controller
After:
dialects_controller
grammar_controller
[Card #42](https://trello.com/c/MWOLFkNG)

[Card #42] Refactor api when loading

---

app/controllers/api/grammars_controller.rb

Need to pass grammar id to calculate quiz completion count.
[Card #48](https://trello.com/c/M9dRaeEL)

[Fix] add grammar id on quiz
